title: Junge Pfarre Baden St. Stephan
description: >
  Suchst du nach einer coolen, jungen Gemeinschaft im Herzen Badens?
  Auf der Webseite der Jungen Pfarre Baden St. Stephan
  findest du unsere aktuellen Termine, Fotos von unseren
  Veranstaltungen und Infos über unsere Gemeinschaft aus
  Jugendlichen und jungen Erwachsenen.
short_description: Termine und Fotos der Jungen Pfarre
email: jugend@baden-st-stephan.at

lang: de_DE

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/flyer"
    values:
      flyer: true

markdown: kramdown

permalink: :title

plugins:
  - jekyll-coffeescript

repository: junge-pfarre/junge-pfarre.github.io

host: 0.0.0.0

theme: jekyll-theme-slate
